'use client'
/**
 * Add patient page (doctor dashboard, abridged sample).
 *
 * One form creates the patient file together with its first treatment:
 * personal data, illnesses, treated teeth (with optional per-tooth notes),
 * the first payment (with its own currency) and photos. The access code is
 * generated by the server and shown on the new profile page.
 */
import React, { useState } from "react";
import { useRouter } from "next/navigation";
import TeethSelector from "@/components/ui/teeth/teethSelector";
import Select from "@/components/form/Select";
import Input from "@/components/form/input/InputField";
import Button from "@/components/ui/button/Button";
import { CURRENCY_OPTIONS } from "@/hooks/usePatientPatch";
import { normalizeDigits } from "@/utils/normalizeDigits";

type Tooth = { id: string; value: string };
type Custom = { id: string; value: string; customTreatment: string };

export default function AddPatientPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [teeth, setTeeth] = useState<Tooth[]>([]);
  const [custom, setCustom] = useState<Custom[]>([]);
  const [images, setImages] = useState<File[]>([]);

  const [form, setForm] = useState({
    name: "", age: "", phone: "", work: "", info: "", medicines: "",
    treatmentName: "", treatmentCost: "", treatmentCurrency: "SYP", // currency of the treatment price
    payment: "", paymentCurrency: "SYP",                              // currency of the first payment (independent)
  });

  const set = (name: keyof typeof form, value: string) =>
    setForm((p) => ({ ...p, [name]: name === "phone" ? normalizeDigits(value) : value }));

  function validate() {
    const e: Record<string, string> = {};
    if (!form.name.trim()) e.name = "Name is required";
    if (!form.phone.trim()) e.phone = "Phone is required";
    if (!form.age.trim()) e.age = "Age is required";
    if (!form.treatmentName.trim()) e.treatmentName = "Treatment name is required";
    if (!(Number(form.treatmentCost) > 0)) e.treatmentCost = "Cost must be a positive number";
    if (!teeth.length) e.teeth = "Select at least one tooth";
    setErrors(e);
    return !Object.keys(e).length;
  }

  async function submit(ev: React.FormEvent) {
    ev.preventDefault();
    if (!validate()) return;
    setLoading(true);

    try {
      // Nested objects travel as JSON strings inside a multipart body (images need multipart).
      const treatments = [{
        treatmentNames: [{ name: form.treatmentName.trim() }],
        cost: Number(form.treatmentCost),
        currency: form.treatmentCurrency,
        teeth: teeth.map((t) => ({ ...t, customTreatment: custom.find((c) => c.id === t.id)?.customTreatment || "" })),
        sessions: form.payment
          ? [{ Payments: form.payment, paymentCurrency: form.paymentCurrency }]
          : [],
      }];

      const body = new FormData();
      (["name", "age", "phone", "work", "info"] as const).forEach((k) => body.append(k, form[k].trim()));
      body.append("treatments", JSON.stringify(treatments));
      body.append(
        "Medicines",
        JSON.stringify(form.medicines.split("-").map((m) => m.trim()).filter(Boolean).map((medicine) => ({ medicine })))
      );
      images.forEach((f) => body.append("images", f));

      const res = await fetch("/api/patients", { method: "POST", body, credentials: "include" });
      if (res.ok) {
        const { data } = await res.json();
        router.push(`/dashboard/profile/${data.patientId}`); // jump straight to the new file
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  return (
    <form onSubmit={submit} className="space-y-4">
      {/* Layout markup omitted in this sample: one card per section (personal data, medical data, treatment, photos). */}
      <Input value={form.name} onChange={(e) => set("name", e.target.value)} placeholder="Name" />
      {errors.name && <p className="text-red-500 text-sm">{errors.name}</p>}

      <div className="flex gap-2">
        <Input value={form.treatmentCost} onChange={(e) => set("treatmentCost", e.target.value)} placeholder="Cost" />
        <Select options={CURRENCY_OPTIONS} defaultValue={form.treatmentCurrency} onChange={(v) => set("treatmentCurrency", v)} />
      </div>

      <div className="flex gap-2">
        <Input value={form.payment} onChange={(e) => set("payment", e.target.value)} placeholder="First payment" />
        <Select options={CURRENCY_OPTIONS} defaultValue={form.paymentCurrency} onChange={(v) => set("paymentCurrency", v)} />
      </div>

      <TeethSelector
        enableCustomTreatments
        initialSelected={[]}
        onSelectionChange={(selected: Tooth[], c?: Custom[]) => { setTeeth(selected); setCustom(c || []); }}
      />
      {errors.teeth && <p className="text-red-500 text-sm">{errors.teeth}</p>}

      <input type="file" accept="image/*" multiple onChange={(e) => setImages(Array.from(e.target.files || []))} />

      <Button type="submit" disabled={loading}>{loading ? "Saving..." : "Create patient file"}</Button>
    </form>
  );
}
